version: '3.9'
services:
  api:
    container_name: graphql_server
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 4000:4000
      - 5555:5555
  # client:
  #   platform: linux/amd64
  #   container_name: blog_client
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client:/app
